#!/usr/bin/env bash
# Bootstrap the Recipe Manager stack on a fresh host.
#
# - Ensures Docker + Docker Compose are available.
# - Creates a `.env` file with a random SECRET_KEY if one does not exist.
# - Makes sure the external `stack_lab-internal` network (used by the
#   Cloudflare Tunnel) exists.
# - Builds and starts the containers in detached mode.
#
# Safe to re-run: it will not overwrite an existing `.env` or network.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

log() { printf '\033[1;34m[deploy]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[deploy]\033[0m %s\n' "$*" >&2; }
err() { printf '\033[1;31m[deploy]\033[0m %s\n' "$*" >&2; }

COMPOSE_FILE="${COMPOSE_FILE:-docker-compose.yml}"
EXTERNAL_NETWORK="${EXTERNAL_NETWORK:-stack_lab-internal}"
ENV_FILE="${ENV_FILE:-.env}"

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    err "Required command '$1' not found in PATH."
    exit 1
  fi
}

compose() {
  docker compose -f "$COMPOSE_FILE" "$@"
}

require_cmd docker
if ! docker compose version >/dev/null 2>&1; then
  err "'docker compose' plugin not available. Install Docker Compose v2."
  exit 1
fi

if [ ! -f "$COMPOSE_FILE" ]; then
  err "Compose file '$COMPOSE_FILE' not found (run from the repo root)."
  exit 1
fi

if [ ! -f "$ENV_FILE" ]; then
  log "Creating $ENV_FILE with a freshly generated SECRET_KEY."
  SECRET_KEY="$(openssl rand -hex 32 2>/dev/null || head -c 32 /dev/urandom | xxd -p -c 64)"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/deploy.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
SECRET_KEY=$SECRET_KEY
# Host port the frontend is published on (see docker-compose.yml).
# PORT=3000
EOF
else
  log "$ENV_FILE already exists; leaving it untouched."
fi

if ! docker network inspect "$EXTERNAL_NETWORK" >/dev/null 2>&1; then
  warn "External network '$EXTERNAL_NETWORK' not found; creating it."
  docker network create "$EXTERNAL_NETWORK" >/dev/null
else
  log "External network '$EXTERNAL_NETWORK' already exists."
fi

log "Building images..."
compose build

log "Starting stack in detached mode..."
compose up -d --remove-orphans

log "Current status:"
compose ps

log "Deploy complete. Point your Cloudflare Tunnel at the 'frontend' service."
